[package]
name = "json2nix-code-theme-generator"
description = "Tool to create the CSS code theme for json2nix-web"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "json2nix-code-theme-generator"
path = "src/main.rs"

[dependencies]
clap.workspace = true
syntect.workspace = true
two-face.workspace = true
