[workspace]
resolver = "3"
members = ["json2nix*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["SteveBinary"]
repository = "https://github.com/SteveBinary/json2nix"
license = "MIT"

[workspace.dependencies]
json2nix = { path = "json2nix" }

clap = { version = "4", features = ["derive"] }
leptos = { version = "0.8", features = ["csr"] }
leptos-use = "0.18"
serde_json = { version = "1", features = ["preserve_order"] }
syntect = { version = "5", default-features = false, features = ["html"] }
two-face = { version = "0.5", default-features = false, features = ["syntect-fancy"] }
wasm-bindgen = "=0.2.114"

[profile.release-for-web]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "s"
strip = "debuginfo"
