use clap::Parser;
use std::process::ExitCode;
use syntect::html::{ClassStyle, css_for_theme_with_class_style};
use two_face::theme::{EmbeddedLazyThemeSet, EmbeddedThemeName, extra};

#[derive(Parser, Debug)]
#[command(version, about)]
enum Command {
    /// Generate the CSS theme with the specified dark and light variations
    Generate {
        /// Name of the dark theme
        #[arg(short, long)]
        dark: String,

        /// Number of the light theme
        #[arg(short, long)]
        light: String,

        /// Common prefix for all generated CSS classes
        #[arg(short, long)]
        class_prefix: Option<String>,
    },
    /// Print all available themes
    List,
}

fn main() -> ExitCode {
    match Command::parse() {
        Command::List => {
            for name in EmbeddedLazyThemeSet::theme_names() {
                println!("{}", name.as_name());
            }

            ExitCode::SUCCESS
        }
        Command::Generate {
            dark: dark_name,
            light: light_name,
            class_prefix,
        } => {
            let theme_set = extra();
            let class_style = match class_prefix {
                None => ClassStyle::Spaced,
                Some(prefix) => ClassStyle::SpacedPrefixed {
                    prefix: Box::new(prefix).leak(),
                },
            };

            let Some(dark_theme) = get_theme(&dark_name) else {
                eprintln!("ERROR: Theme doesn't exist: {dark_name}");
                return ExitCode::FAILURE;
            };
            let Some(light_theme) = get_theme(&light_name) else {
                eprintln!("ERROR: Theme doesn't exist: {dark_name}");
                return ExitCode::FAILURE;
            };

            let dark_theme = theme_set.get(dark_theme);
            let light_theme = theme_set.get(light_theme);

            let dark_css = match css_for_theme_with_class_style(dark_theme, class_style) {
                Ok(css) => css,
                Err(err) => {
                    eprintln!("ERROR: failed to create CSS from dark theme: {}", err.to_string());
                    return ExitCode::FAILURE;
                }
            };

            let light_css = match css_for_theme_with_class_style(light_theme, class_style) {
                Ok(css) => css,
                Err(err) => {
                    eprintln!("ERROR: failed to create CSS from light theme: {}", err.to_string());
                    return ExitCode::FAILURE;
                }
            };

            let final_css = format!(
                r#"/* generated by json2nix-code-theme-generator */

@media (prefers-color-scheme: dark) {{
{dark_css}
}} /* end of dark theme: {dark_name} */

@media (prefers-color-scheme: light) {{
{light_css}
}} /* end of light theme: {light_name} */"#
            );

            println!("{final_css}");

            ExitCode::SUCCESS
        }
    }
}

fn get_theme(name: &str) -> Option<EmbeddedThemeName> {
    EmbeddedLazyThemeSet::theme_names()
        .iter()
        .find(|theme| theme.as_name() == name)
        .map(Clone::clone)
}
